name: Build and Test

on:
  # Run any time code is pushed to main.
  push:
    branches:
      - main

  # Run on all pull requests
  pull_request:

  workflow_dispatch:

jobs:
  build-and-test-ios:
    name: Build Combine Extensions iOS
    uses: krogerco/Shared-CI-Workflow-iOS/.github/workflows/build.yml@v2
    with:
      FILENAME: CombineExtensions.xcworkspace
